// "use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { Toaster } from "components/ui/toaster";
import Providers from "components/Providers";

const inter = Inter({ subsets: ["latin"] });
//Google Inter font import

export const metadata = {
  title: "vnRoadmaps",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  // const locale = useLocale();

  // Show a 404 error if the user requests an unknown locale
  // if (params.locale !== locale) {
  //   notFound();
  // }

  return (
    <html
      lang={"vi"} // locale : [vi, en]
      suppressHydrationWarning //This attr can suppress hydrate warning
    >
      <body className={inter.className}>
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
